### ISSUE TITLE
rpi3 issue: Tag 123 not found

### ISSUE THREAD

**Issue by v-marinkov** [home-assistant/hassio-build#104]
Hi, I am running 
```
curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s -- -m raspberrypi3
```
on a raspberry pi 3 with latest Raspbian 9 lite and I get the following error
```
[Info] Install supervisor docker
Tag 123 not found in repository docker.io/homeassistant/armhf-hassio-supervisor
```
I am running under `sudo su` and all dependencies have been installed.
What could be going wrong?
Thanks!

**Comment by v-marinkov** [comment]
I suppose it has to do with the latest update to Hassio 123?

**Comment by pvizeli** [comment]
Do you have install docker-ce ? Which docker-ce version do you have install?

**Comment by pvizeli** [comment]
Can you try it agen?

The tag is exists: https://hub.docker.com/r/homeassistant/armhf-hassio-supervisor/tags/

**Comment by v-marinkov** [comment]
OK it's fixed. The problem occurs when I install docker using `sudo apt install docker.io`. The package `docker-ce` cannot be found even after adding the repository.
What fixed the problem was using the automated convenience scripts from here: [https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-convenience-script](https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-convenience-script)
```
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
``` 
and then the script from the install instructions here.
