### ISSUE TITLE
hassio_install doesn't pull the latest homeassistant image

### ISSUE THREAD

**Issue by thehomerepot** [home-assistant/hassio-build#111]
I installed hassio and homeassistant using the hassio_install script. It initially pulled the latest homeassistant image, which at the time was 0.75. There was a bug in 0.75 that prevented the hassio tab from loading, and therefore you couldn't upgrade homeassistant.

Re-running the install script will always pull the latest hassio image, but uses the pre-existing homeassistant image. I manually did a docker pull for the latest homeassistant image which resolved my issue.

Any reason why the hassio_install script doesn't force pull the latest version of the container?

**Comment by pvizeli** [comment]
You need remove the docker image and they will it download again. otherwise you update it over home-assistant api -> /api/hassio/homeassistant/update -> https://developers.home-assistant.io/docs/en/external_api_rest.html

**Comment by thehomerepot** [comment]
Why require the user to delete the existing image? If they're running the install script again, wouldn't automatically pulling the latest image make more sense? The script already does this for the hassio_supervisor image, why not do it for homeassistant as well?

**Comment by pvizeli** [comment]
Because that is a task for supervisor. The install script only install Hass.io and work like the images they also not shipping homeassistant

**Comment by pvizeli** [comment]
But you can also run `docker pull homeassistan/xyz-homeassistant` and restart systemd service hassio-supervisor

**Comment by thehomerepot** [comment]
> Because that is a task for supervisor. The install script only install Hass.io and work like the images they also not shipping homeassistant

Ok, that's fair. Any reason why on creation of a **new** homeassistant docker container, the supervisor wouldn't download the latest image first? It just seems un-intuitive that an old broken image version would be perpetuated and require manual intervention from me to update. I understand why it wouldn't auto-update an existing container, but I would expect a brand new instance of homeassistant to pull the latest.
