### ISSUE TITLE
Invalid Reference format

### ISSUE THREAD

**Issue by mhutton81** [home-assistant/hassio-build#115]
When I run the installer script
 `curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s` 
I get the following error

`root@homeassistant:/home/ha# curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s

[Info] Install supervisor docker
invalid reference format`

is there a log what is created I am having difficulty finding any useful information

thanks

**Comment by pvizeli** [comment]
I think the script can't detect the correct cpu architecture. Try to set a machine with `-m ...`

**Comment by mrlook2** [comment]
I have the same issue running a ubuntu 18.04 under vmware. 
What machine type hould I use? I have tried them all but no luck.

**Comment by malamaker** [comment]
I am having the same issue running on Ubuntu 18.04 as well.

**Comment by frenck** [comment]
For reference, a valid list of commands to use from a clean ubuntu installation.

https://gist.github.com/frenck/32b4f74919ca6b95b30c66f85976ec58

This ^^ has been used by many and is derived from the `hassio-vagrant` machine.
