### ISSUE TITLE
working in the CLI once running

### ISSUE THREAD

**Issue by jmesberg** [home-assistant/hassio-build#118]
please excuse me if these are basic docker questions vs hassio questions. 
I got this up and running very easily on my NUC. I'm used to managing my yaml files from a CLI within the filesystem of my RPI (typically I use Nano), but so far I see that none of my normal CLI commands (including nano) are available from the bash shell within the container. 
(Note: I got to the bash shell with this command sudo docker exec -t -i homeassistant /bin/bash). Even the typical hassio CLI commands don't seem to be available. 

Any suggestions?

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
