### ISSUE TITLE
SSH Server won't start (button goes Red....no entry in log)

### ISSUE THREAD

**Issue by jmesberg** [home-assistant/hassio-build#119]
I believe this is a known issue but I can't see that anyone has documented a solution so far. If I can't use the bash shell in the container to edit my yaml files (see previous issue logged) and I can't SSH in, then how are users managing their HA files?

Clearly I'm missing something!

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
