### ISSUE TITLE
Please don't just brutally restart my docker deamon

### ISSUE THREAD

**Issue by olemartinorg** [home-assistant/hassio-build#127]
I ran the installation instructions for the 'hassio_install' script and it suddenly restarted my docker deamon, thus also restarting my OctoPrint server, thereby aborting my ongoing 3d-print. It's not cool to just forcefully restart services on my system without asking.

Guess I'll throw away the wasted plastic and start again!

**Comment by frenck** [comment]
The current script has been modified to only do this, in case it is really needed.
For newer Docker version (18.09+) it won't reboot anymore.

We keep this mechanism around for the older versions for now.
