### ISSUE TITLE
No mapping for /backup, so core components cannot access that folder

### ISSUE THREAD

**Issue by regystro** [home-assistant/hassio-build#129]
Hi. I'm trying to use [Folder Watcher](https://www.home-assistant.io/components/folder_watcher/) to monitor the /backup folder, but when I add it to [whitelist_external_dirs](https://www.home-assistant.io/docs/configuration/basic/) the config check reports `not a directory @ data['whitelist_external_dirs'][0]`.
Issuing a `docker inspect homeassistant` I can see there are mounts for /config, /ssl and /share:
```
   "HostConfig": {
            "Binds": [
                "/usr/share/hassio/homeassistant:/config:rw",
                "/usr/share/hassio/ssl:/ssl:ro",
                "/usr/share/hassio/share:/share:rw"
            ]
```
...but /backup is missing, so no core components can access that folder. Is this by design? How can I monitor /backup folder then?

Here's my /etc/hassio.json:
```
{
    "supervisor": "homeassistant/armhf-hassio-supervisor",
    "homeassistant": "homeassistant/raspberrypi3-homeassistant",
    "data": "/usr/share/hassio"
}
```
and my /usr/share/hassio/updater.json which stands the current versions I'm running:
```
{
  "channel": "stable",
  "hassio": "140",
  "homeassistant": "0.82.1"
}
```

Thank you in advance.

**Comment by aheath70** [comment]
Exact same issue here. Running Hass.io 0.88.2, RPi Model 3 B+, HassOS. Adding whitelist into configuration.yaml 
```
whitelist_external_dirs:
- /backup
```
results in an error during config check.
```
Configuration invalid
not a directory @ data['whitelist_external_dirs'][1]
```
whereas adding
``` 
whitelist_external_dirs:
- /share
```
passes configuration successfully and the folder is available for folder_watcher component.

**Comment by metbril** [comment]
cc @robmarkcole

**Comment by robmarkcole** [comment]
I guess this is one for @pvizeli

**Comment by SH-Solutions** [comment]
Same problem here. I'm currently on version 0.94.4.
