### ISSUE TITLE
Setup failed for hassio: Component failed to initialize.

### ISSUE THREAD

**Issue by eskimos2000** [home-assistant/hassio-build#130]
Hi,

I have installed as describe here hassio o Odroid HC2 (using machine odroid-xu), Everything went without error (I did not installed network-manager only). After some time I was able to connect to HA on port 8123 set up password and it seems working well but I have an error that hassio component can not be start check config. I have hassio: in my configuration.yaml.

`2018-11-30 04:01:12 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2018-11-30 04:01:12 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /supervisor/ping request
2018-11-30 04:01:12 ERROR (MainThread) [homeassistant.components.hassio] Not connected with Hass.io
2018-11-30 04:01:12 INFO (MainThread) [homeassistant.setup] Setup of domain hassio took 10.0 seconds.
2018-11-30 04:01:12 ERROR (MainThread) [homeassistant.setup] Setup failed for hassio: Component failed to initialize.
2018-11-30 04:01:12 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 13.93s
`

I am using Portrainer to control containers and I see both HA and Hassio are running. 
But Hassio-supervisior has an errors as well:
`[32m18-11-30 04:00:23 INFO (MainThread) [__main__] Initialize Hass.io setup[0m
[32m18-11-30 04:00:23 INFO (MainThread) [__main__] Setup HassIO[0m
[32m18-11-30 04:00:23 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/armhf-hassio-supervisor with version 140[0m
[32m18-11-30 04:00:23 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.systemd1 on /org/freedesktop/systemd1[0m
[32m18-11-30 04:00:23 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1[0m
[32m18-11-30 04:00:23 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.hostname1 on /org/freedesktop/hostname1[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.utils.gdbus] Introspect de.pengutronix.rauc on /[0m
[31m18-11-30 04:00:24 ERROR (MainThread) [hassio.utils.gdbus] DBus return error: b'Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name de.pengutronix.rauc was not provided by any .service files\n'[0m
[33m18-11-30 04:00:24 WARNING (MainThread) [hassio.dbus.rauc] Can't connect to rauc[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.host.info] Update local host information[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.host.services] Update service information[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.host.services] Reload local service hassio-apparmor.service[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1[0m
[32m18-11-30 04:00:24 INFO (SyncWorker_1) [hassio.docker.interface] Attach to image homeassistant/odroid-xu-homeassistant with version 0.82.1[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.addons.git] Load add-on /data/addons/core repository[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.addons.git] Load add-on /data/addons/git/a0d7b954 repository[0m
[32m18-11-30 04:00:24 INFO (MainThread) [hassio.addons] Load add-ons: 47 all - 47 new - 0 remove[0m
[32m18-11-30 04:00:25 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json[0m
[32m18-11-30 04:00:27 INFO (MainThread) [hassio.snapshots] Found 0 snapshot files[0m
[32m18-11-30 04:00:27 INFO (MainThread) [hassio.discovery] Load 0 messages[0m
[32m18-11-30 04:00:27 INFO (MainThread) [__main__] Run Hass.io[0m
[32m18-11-30 04:00:27 INFO (MainThread) [hassio.misc.dns] Start DNS port forwarding for host add-ons[0m
[32m18-11-30 04:00:27 INFO (MainThread) [hassio.core] Ignore Hass.io auto updates on dev channel[0m
[32m18-11-30 04:00:27 INFO (MainThread) [hassio.api] Start API on 172.30.32.2[0m
[32m18-11-30 04:00:27 INFO (MainThread) [hassio.addons] Startup initialize run 0 add-ons[0m
[32m18-11-30 04:00:27 INFO (MainThread) [hassio.core] Hass.io reboot detected[0m
[32m18-11-30 04:00:27 INFO (MainThread) [hassio.tasks] All core tasks are scheduled[0m
[32m18-11-30 04:00:27 INFO (MainThread) [hassio.core] Hass.io is up and running[0m
[33m18-11-30 04:00:42 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home Assistant Docker![0m
[32m18-11-30 04:00:42 INFO (SyncWorker_5) [hassio.docker.interface] Clean homeassistant/odroid-xu-homeassistant Docker application[0m
[32m18-11-30 04:00:44 INFO (SyncWorker_5) [hassio.docker.homeassistant] Start homeassistant homeassistant/odroid-xu-homeassistant with version 0.82.1[0m
[33m18-11-30 04:12:23 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home Assistant startup![0m
[31m18-11-30 04:12:23 ERROR (MainThread) [hassio.tasks] Watchdog Home Assistant reanimation fails![0m`

Help please?

**Comment by rbray89** [comment]
Hmmm... that's a recently "supported" board. What is the host kernel version? Dbus version? Docker version?

I ordered an XU4 to port to HassOS to, so I'll be starting that this weekend with any luck.

**Comment by pvizeli** [comment]
Please use the installer. Hass.io will never run with as a portainer setup.

**Comment by eskimos2000** [comment]
I used installer as I wrote. I use portrainer only to control containers as
I have a few other.

So after run the script I got above errors.



On Sat., 1 Dec. 2018, 01:59 Pascal Vizeli, <notifications@github.com> wrote

**Comment by eskimos2000** [comment]
This is my docker info:

`Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 18.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9f2e07b1fc1342d1c48fe4d7bbb94cb6d1bf278b.m
runc version: 079817cc26ec5292ac375bb9f47f373d33574949
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.81-1-ARCH
Operating System: Arch Linux ARM
OSType: linux
Architecture: armv7l
CPUs: 8
Total Memory: 1.947GiB
Name: alarm
ID: EDKJ:BE2X:N4P6:GUPO:PBIF:3FRI:XSTI:N4US:HN5X:COTY:K5IC:2ZXX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

Dbus:

`pacman -Qi dbus
Name            : dbus
Version         : 1.12.10-2
Description     : Freedesktop.org message bus system
Architecture    : armv7h
URL             : https://wiki.freedesktop.org/www/Software/dbus/
Licenses        : GPL  custom
Groups          : None
Provides        : libdbus
Depends On      : libsystemd  expat
Optional Deps   : None
Required By     : avahi  libpcap  systemd
Optional For    : None
Conflicts With  : libdbus
Replaces        : libdbus
Installed Size  : 942.00 KiB
Packager        : Arch Linux ARM Build System <builder+xu8@archlinuxarm.org>
Build Date      : Thu Sep 6 05:48:27 2018
Install Date    : Sat Oct 6 00:31:33 2018
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : SHA-256 Sum`

I USED SCRIPT TO INSTALL, please reopen the case.

**Comment by eskimos2000** [comment]
I did reboot and I have run docker logs hassio_supervisor:
All good until:

`18-11-30 07:02:23 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/:
18-11-30 07:02:23 WARNING (MainThread) [hassio.tasks] Watchdog miss API response from Home Assistant
18-11-30 07:07:23 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/:
18-11-30 07:07:23 ERROR (MainThread) [hassio.tasks] Watchdog found a problem with Home Assistant API!
18-11-30 07:07:23 INFO (SyncWorker_34) [hassio.docker.interface] Stop homeassistant/odroid-xu-homeassistant Docker application
18-11-30 07:07:28 INFO (SyncWorker_34) [hassio.docker.interface] Clean homeassistant/odroid-xu-homeassistant Docker application
18-11-30 07:07:34 INFO (SyncWorker_35) [hassio.docker.homeassistant] Start homeassistant homeassistant/odroid-xu-homeassistant with version 0.82.1
18-11-30 07:19:11 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home Assistant startup!
18-11-30 07:19:11 ERROR (MainThread) [hassio.tasks] Watchdog Home Assistant reanimation fails!`

docker logs homeassistant:

All good apart of that:

`2018-12-01 01:08:53 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2018-12-01 01:08:53 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /supervisor/ping request
2018-12-01 01:08:53 ERROR (MainThread) [homeassistant.components.hassio] Not connected with Hass.io
2018-12-01 01:08:53 INFO (MainThread) [homeassistant.setup] Setup of domain hassio took 10.0 seconds.
2018-12-01 01:08:53 ERROR (MainThread) [homeassistant.setup] Setup failed for hassio: Component failed to initialize.
2018-12-01 01:08:53 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 14.64s
2018-12-01 01:08:53 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2018-12-01 01:08:53 INFO (MainThread) [homeassistant.core] Timer:starting`

Please help.

**Comment by eskimos2000** [comment]
I did another reboot and hassio logs looks clean only: 
`01:47:02 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home Assistant startup!`

Homeassistant logs looks the same:

 `2018-12-01 01:08:53 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds. 2018-12-01 01:08:53 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /supervisor/ping request 2018-12-01 01:08:53 ERROR (MainThread) [homeassistant.components.hassio] Not connected with Hass.io 2018-12-01 01:08:53 INFO (MainThread) [homeassistant.setup] Setup of domain hassio took 10.0 seconds. 2018-12-01 01:08:53 ERROR (MainThread) [homeassistant.setup] Setup failed for hassio: Component failed to initialize. 2018-12-01 01:08:53 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 14.64s 2018-12-01 01:08:53 INFO (MainThread) [homeassistant.core] Starting Home Assistant 2018-12-01 01:08:53 INFO (MainThread) [homeassistant.core] Timer:starting`
