### ISSUE TITLE
19-01-25 16:58:35 ERROR (SyncWorker_13) [hassio.docker.interface] Can't install homeassistant/armv7l-homeassistant:landingpage -> 404 Client Error: Not Found ("pull access denied for homeassistant/armv7l-homeassistant, repository does not exist or may require 'docker login'").

### ISSUE THREAD

**Issue by blackhu** [home-assistant/hassio-build#142]
19-01-25 16:58:35 ERROR (SyncWorker_13) [hassio.docker.interface] Can't install homeassistant/armv7l-homeassistant:landingpage -> 404 Client Error: Not Found ("pull access denied for homeassistant/armv7l-homeassistant, repository does not exist or may require 'docker login'").

**Comment by blackhu** [comment]
I won't be using hassio anymore. It's too unfriendly

**Comment by pimoon** [comment]
solution is in #146
