### ISSUE TITLE
Hass.io only from one device accessible

### ISSUE THREAD

**Issue by ivgg-me** [home-assistant/hassio-build#144]
I have installed Hass.io based on the [guide](https://github.com/home-assistant/hassio-build/blob/master/install/README.md) in this repository on a Raspberry Pi 3 B+ with Raspbian Stretch Lite (which has a fix IP and is accessible only via SSH) and Docker Community Edition (installed using the  [convenience scripts](https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-convenience-script)).

Now I have the problem that I can only access the Home Assistant UI via Chrome from the notebook which I have used to install Hass.io (over SSH) on the Pi. From other devices (like a Android mobile using Chrome) in the same network I can't access the UI.

Has anyone an idea to solve this problem?

Thank you!

**Comment by pvizeli** [comment]
It sounds like you have a firewall enabled. We have also own images for raspberry they solve problems like that :)
