### ISSUE TITLE
Error when building on MacOS: "error creating aufs mount" 

### ISSUE THREAD

**Issue by ubnt-marc-khouri** [home-assistant/hassio-build#67]
When running the builder instruction from [here](https://github.com/home-assistant/hassio-build/tree/master/builder#run) under MacOS, I get the following error:

```
error creating aufs mount to /var/lib/docker/aufs/mnt/ab197f71211cb833b324b17e75c0ba2e0a7f7b2599410238980a9e2b5aa27c9d-init: invalid argument
```

---------------------------------

The solution I found was in [this issue](https://github.com/docker/for-mac/issues/1594#issuecomment-299698273): go to Docker-for-mac preferences > Daemon > Advanced, and add in the `"storage-driver": "aufs"` key

```
{
    ... might have other keys already,
    "storage-driver" : "aufs"
}
```

**Comment by ubnt-marc-khouri** [comment]
Feel free to close this issue (or maybe add the solution to the builder/README?), I created it to document the solution in case other people have the same issue :)

**Comment by pvizeli** [comment]
Would be nice, yes. You can also use the local docker and map the docker.sock into builder.

**Comment by fredrikbaberg** [comment]
This error seem to occur on Ubuntu 18.04 for me (I did the change as written above to change to aufs).

Is there some specific reason this `aufs` error occurs?
