### ISSUE TITLE
Mapping Z-Wave USB when installed from Installer

### ISSUE THREAD

**Issue by zenturacp** [home-assistant/hassio-build#69]
Hi All,

I Run Debian 9 and installed via the Installer and works just PERFECT except for im really too stupid to reverse where the Docker image for Home Assistant is started so I can add the map device to my system??

Can anybody please help me to point in the right direction?

I was in the supervisor docker and trying to reverse the hassio.py but gave up - there must be an option to find the composer config or where the docker runtime is defined?

**Comment by arbreng** [comment]
https://github.com/home-assistant/hassio/blob/dev/hassio/docker/homeassistant.py

Look at the devices() function

**Comment by pvizeli** [comment]
Home Assistant run in privileged modus... They map all device per default.

**Comment by pvizeli** [comment]
Maybe that help: https://github.com/home-assistant/hassio-build/pull/86
