### ISSUE TITLE
Ubuntu install docker container crashes

### ISSUE THREAD

**Issue by darkstar939** [home-assistant/hassio-build#76]
clean install on ubuntu 16.04

using the curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s command:

It does not complete the install.  It appears to install and start the container but the container just crashes and restarts in a loop.  The usr/share/hassio/home-assistant folder is missing everything but apparmor folder.

**Comment by frenck** [comment]
Could you provide some debug output / logs in order for us to being able to address this issue?

**Comment by darkstar939** [comment]
sure can you provide the cli commands to enable debug and directory to find the logs.  Much appreciated.

**Comment by frenck** [comment]
@darkstar939 Just the output of `curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s` would help...

**Comment by darkstar939** [comment]
see the different container ids, it goes up for a second crashes and another replaces it.

**Comment by frenck** [comment]
@darkstar939 The requirements have changes. You need the following packages installed:
-apparmor-utils
- apt-transport-https
- avahi-daemon
- ca-certificates
- curl
- dbus
- jq
- network-manager
- socat
- software-properties-common

Furthermore, `docker.io`, seems to be incorrect. You need docker CE. When in doubt, run their install script using: `curl -sSL https://get.docker.com | sh`.

If all dependecies are setup correctly, running the Hass.io install script should not be a problem.

**Comment by darkstar939** [comment]
@frenck, same thing.

On another clean install these are the commands I ran.
sudo apt-get update && sudo apt-get upgrade --yes
sudo apt-get -y install apparmor-utils apt-transport-https avahi-daemon ca-certificates curl dbus jq network-manager socat software-properties-common bash openssh-server
curl -sSL https://get.docker.com | sh

curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | sudo bash -s

Here is the output I got this time:

linuxbox@linuxbox:~$ curl -sSL https://get.docker.com | sh
# Executing docker install script, commit: 36b78b2
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
+ sudo -E sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial edge" > /etc/apt/sources.list.d/docker.list
+ [ ubuntu = debian ]
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sudo -E sh -c docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:25 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: false
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker linuxbox

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
linuxbox@linuxbox:~$ curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | sudo bash -s
[Info] Install supervisor docker
[Info] Install supervisor startup scripts
Created symlink from /etc/systemd/system/multi-user.target.wants/hassio-supervisor.service to /etc/systemd/system/hassio-supervisor.service.
[Info] Install AppArmor scripts
Created symlink from /etc/systemd/system/multi-user.target.wants/hassio-apparmor.service to /etc/systemd/system/hassio-apparmor.service.
[Info] Run Hass.io

linuxbox@linuxbox:~$ docker container ls --all
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.37/containers/json?all=1: dial unix /var/run/docker.sock: connect: permission denied
linuxbox@linuxbox:~$

**Comment by darkstar939** [comment]
so I downloaded the ubuntu 18.04 iso, loaded up that vm and used the exact same workflow and its up and running.  Not sure what changed but it did have it working for months on ubuntu 16.04.

**Comment by rohitpaul** [comment]
​I tried to install docker-ce on 18.04 and I think, docker hasn't setup the
repos for it just yet. Per there documentaiton, the OS requirements are: OS
requirements

To install Docker CE, you need the 64-bit version of one of these Ubuntu
versions:

   - Artful 17.10 (Docker CE 17.11 Edge and higher only)
   - Xenial 16.04 (LTS)
   - Trusty 14.04 (LTS)

​

**Comment by rohitpaul** [comment]
I tried to install docker-ce on 18.04 and I think, docker hasn't setup the repos for it just yet. Per there documentaiton, the OS requirements are:

> OS requirements
> To install Docker CE, you need the 64-bit version of one of these Ubuntu versions:
> 
> Artful 17.10 (Docker CE 17.11 Edge and higher only)
> Xenial 16.04 (LTS)
> Trusty 14.04 (LTS)

**Comment by darkstar939** [comment]
It worked for me on 18.04 use the command I posted above.




On Monday, May 21, 2018, 5:37 PM, Rohit Paul <notifications@github.com> wrote:

​I tried to install docker-ce on 18.04 and I think, docker hasn't setup the
repos for it just yet. Per there documentaiton, the OS requirements are: OS
requirements

To install Docker CE, you need the 64-bit version of one of these Ubuntu
versions:

 - Artful 17.10 (Docker CE 17.11 Edge and higher only)
 - Xenial 16.04 (LTS)
 - Trusty 14.04 (LTS)

​

**Comment by pvizeli** [comment]
You need run `curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | sudo bash -s`

Ubuntu need a `sudo`

**Comment by darkstar939** [comment]
yeah I noticed, a little late on the response but thanks.
