### ISSUE TITLE
Revised install instructions

### ISSUE THREAD

**Issue by lhassell** [home-assistant/hassio-build#79]
I'm going to freely admit being a bit of a newb here. I have a tiny server running ubuntu 16.04 LTE (AMD Athlon P340, 4 GB mem), and I'd like to keep everything on it rather than add another Pi to the mix. I've tried rebuilding it multiple times and cannot get this running. It looks like the setup has changed in the last few days. Is there going to be a revision to the installation guide? I know you don't owe me anything, I'm just looking for some guidance on my best course of action, as I really like the ease of use of running hass.io vs standalone home assistant. Thanks in advance.

**Comment by ciotlosm** [comment]
@lhassell are you using generic linux install ?

**Comment by lhassell** [comment]
No. I was using the process described here: https://github.com/home-assistant/hassio-build/tree/master/install#install-hassio

I wanted to preserve the addon and upgrade functionality of hass.io, to make management easier.

**Comment by ciotlosm** [comment]
@lhassell that is generic linux install of hassio. Which means you should have run the below command considering you're on an AMD Athlon:
```
curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s -- -m qemux86-64
```

**Comment by lhassell** [comment]
That is the command I used, including the machine definition, but it just cycles the supervisor image and never makes it all the way up.

**Comment by pvizeli** [comment]
can you post the `journalctl -f` after you run the install script? And also the `dmesg`

**Comment by lhassell** [comment]
When I execute

>  journalctl -f

I get the following. It just kept repeating til I escaped out.

> May 29 21:37:53 Docker-1 systemd[1]: hassio-supervisor.service: Service hold-off time over, scheduling restart.
> May 29 21:37:53 Docker-1 systemd[1]: Stopped Hass.io supervisor.
> May 29 21:37:53 Docker-1 systemd[1]: Starting Hass.io supervisor...
> May 29 21:37:53 Docker-1 docker[9902]: hassio_supervisor
> May 29 21:37:53 Docker-1 systemd[1]: Started Hass.io supervisor.
> May 29 21:37:54 Docker-1 systemd-udevd[9961]: Could not generate persistent MAC address for veth3714121: No such file or directory
> May 29 21:37:54 Docker-1 systemd-udevd[9962]: Could not generate persistent MAC address for veth755c04d: No such file or directory
> May 29 21:37:54 Docker-1 kernel: docker0: port 2(veth755c04d) entered blocking state
> May 29 21:37:54 Docker-1 kernel: docker0: port 2(veth755c04d) entered disabled state
> May 29 21:37:54 Docker-1 kernel: device veth755c04d entered promiscuous mode
> May 29 21:37:54 Docker-1 kernel: IPv6: ADDRCONF(NETDEV_UP): veth755c04d: link is not ready
> May 29 21:37:54 Docker-1 dockerd[20640]: time="2018-05-29T21:37:54.261621058-05:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]"
> May 29 21:37:54 Docker-1 dockerd[20640]: time="2018-05-29T21:37:54.261692163-05:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
> May 29 21:37:54 Docker-1 NetworkManager[9811]: <info>  [1527647874.3745] devices added (path: /sys/devices/virtual/net/veth3714121, iface: veth3714121)
> May 29 21:37:54 Docker-1 NetworkManager[9811]: <info>  [1527647874.3746] device added (path: /sys/devices/virtual/net/veth3714121, iface: veth3714121): no ifupdown configuration found.
> May 29 21:37:54 Docker-1 NetworkManager[9811]: <info>  [1527647874.3917] devices added (path: /sys/devices/virtual/net/veth755c04d, iface: veth755c04d)
> May 29 21:37:54 Docker-1 NetworkManager[9811]: <info>  [1527647874.3918] device added (path: /sys/devices/virtual/net/veth755c04d, iface: veth755c04d): no ifupdown configuration found.
> May 29 21:37:54 Docker-1 NetworkManager[9811]: <info>  [1527647874.3933] manager: (veth3714121): new Veth device (/org/freedesktop/NetworkManager/Devices/38168)
> May 29 21:37:54 Docker-1 NetworkManager[9811]: <info>  [1527647874.4206] manager: (veth755c04d): new Veth device (/org/freedesktop/NetworkManager/Devices/38169)
> May 29 21:37:54 Docker-1 dockerd[20640]: time="2018-05-29T21:37:54-05:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/e66b1554dd351cd25f36f91df0eff12a42fb073908e40ef34fceba0972b728cf/shim.sock" debug=false module="containerd/tasks" pid=9976
> May 29 21:37:54 Docker-1 kernel: eth0: renamed from veth3714121
> May 29 21:37:54 Docker-1 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth755c04d: link becomes ready
> May 29 21:37:54 Docker-1 kernel: docker0: port 2(veth755c04d) entered blocking state
> May 29 21:37:54 Docker-1 kernel: docker0: port 2(veth755c04d) entered forwarding state
> May 29 21:37:55 Docker-1 NetworkManager[9811]: <info>  [1527647875.0447] devices removed (path: /sys/devices/virtual/net/veth3714121, iface: veth3714121)
> May 29 21:37:55 Docker-1 NetworkManager[9811]: <info>  [1527647875.0448] device (veth3714121): driver 'veth' does not support carrier detection.
> May 29 21:37:55 Docker-1 NetworkManager[9811]: <info>  [1527647875.0453] device (veth755c04d): link connected
> May 29 21:37:55 Docker-1 kernel: kauditd_printk_skb: 2 callbacks suppressed
> May 29 21:37:55 Docker-1 kernel: audit: type=1400 audit(1527647875.146:250379): apparmor="DENIED" operation="open" profile="hassio-supervisor" name="/" pid=9995 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 audit[9995]: AVC apparmor="DENIED" operation="open" profile="hassio-supervisor" name="/" pid=9995 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 audit[9995]: AVC apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=9995 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 audit[9995]: AVC apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=9995 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 kernel: audit: type=1400 audit(1527647875.170:250380): apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=9995 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 kernel: audit: type=1400 audit(1527647875.171:250381): apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=9995 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 kernel: audit: type=1400 audit(1527647875.171:250382): apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=9995 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 audit[9995]: AVC apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=9995 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 audit[9995]: AVC apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=9995 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 kernel: audit: type=1400 audit(1527647875.172:250383): apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=9995 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 audit[9995]: AVC apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/math.cpython-36m-x86_64-linux-gnu.so" pid=9995 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 kernel: audit: type=1400 audit(1527647875.203:250384): apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/math.cpython-36m-x86_64-linux-gnu.so" pid=9995 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]: Traceback (most recent call last):
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/asyncio/__init__.py", line 9, in <module>
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:     from . import selectors
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]: ImportError: cannot import name 'selectors'
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]: During handling of the above exception, another exception occurred:
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]: Traceback (most recent call last):
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:     "__main__", mod_spec)
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:     exec(code, run_globals)
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/site-packages/hassio/__main__.py", line 2, in <module>
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:     import asyncio
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/asyncio/__init__.py", line 11, in <module>
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:     import selectors  # Will also be exported.
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/selectors.py", line 10, in <module>
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]:     import math
> May 29 21:37:55 Docker-1 hassio-supervisor[9922]: ImportError: Error loading shared library /usr/lib/python3.6/lib-dynload/math.cpython-36m-x86_64-linux-gnu.so: Permission denied
> May 29 21:37:55 Docker-1 dockerd[20640]: time="2018-05-29T21:37:55-05:00" level=info msg="shim reaped" id=e66b1554dd351cd25f36f91df0eff12a42fb073908e40ef34fceba0972b728cf module="containerd/tasks"
> May 29 21:37:55 Docker-1 dockerd[20640]: time="2018-05-29T21:37:55.427719534-05:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
> May 29 21:37:55 Docker-1 kernel: docker0: port 2(veth755c04d) entered disabled state
> May 29 21:37:55 Docker-1 kernel: veth3714121: renamed from eth0
> May 29 21:37:55 Docker-1 kernel: docker0: port 2(veth755c04d) entered disabled state
> May 29 21:37:55 Docker-1 kernel: device veth755c04d left promiscuous mode
> May 29 21:37:55 Docker-1 kernel: docker0: port 2(veth755c04d) entered disabled state
> May 29 21:37:55 Docker-1 NetworkManager[9811]: <info>  [1527647875.6476] devices added (path: /sys/devices/virtual/net/veth3714121, iface: veth3714121)
> May 29 21:37:55 Docker-1 NetworkManager[9811]: <info>  [1527647875.6477] device added (path: /sys/devices/virtual/net/veth3714121, iface: veth3714121): no ifupdown configuration found.
> May 29 21:37:55 Docker-1 NetworkManager[9811]: <info>  [1527647875.7912] devices removed (path: /sys/devices/virtual/net/veth3714121, iface: veth3714121)
> May 29 21:37:55 Docker-1 NetworkManager[9811]: <info>  [1527647875.7913] devices removed (path: /sys/devices/virtual/net/veth755c04d, iface: veth755c04d)
> May 29 21:37:55 Docker-1 NetworkManager[9811]: <info>  [1527647875.9071] device (veth755c04d): driver 'veth' does not support carrier detection.
> May 29 21:37:56 Docker-1 hassio-supervisor[9922]: hassio_supervisor
> May 29 21:37:56 Docker-1 systemd-udevd[10117]: Could not generate persistent MAC address for vethc059b83: No such file or directory
> May 29 21:37:56 Docker-1 kernel: docker0: port 2(veth0b3f2c6) entered blocking state
> May 29 21:37:56 Docker-1 kernel: docker0: port 2(veth0b3f2c6) entered disabled state
> May 29 21:37:56 Docker-1 kernel: device veth0b3f2c6 entered promiscuous mode
> May 29 21:37:56 Docker-1 kernel: IPv6: ADDRCONF(NETDEV_UP): veth0b3f2c6: link is not ready
> May 29 21:37:56 Docker-1 systemd-udevd[10118]: Could not generate persistent MAC address for veth0b3f2c6: No such file or directory
> May 29 21:37:56 Docker-1 dockerd[20640]: time="2018-05-29T21:37:56.861373191-05:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]"
> May 29 21:37:56 Docker-1 dockerd[20640]: time="2018-05-29T21:37:56.861437113-05:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
> May 29 21:37:56 Docker-1 NetworkManager[9811]: <info>  [1527647876.9613] devices added (path: /sys/devices/virtual/net/vethc059b83, iface: vethc059b83)
> May 29 21:37:56 Docker-1 NetworkManager[9811]: <info>  [1527647876.9614] device added (path: /sys/devices/virtual/net/vethc059b83, iface: vethc059b83): no ifupdown configuration found.
> May 29 21:37:56 Docker-1 NetworkManager[9811]: <info>  [1527647876.9788] devices added (path: /sys/devices/virtual/net/veth0b3f2c6, iface: veth0b3f2c6)
> May 29 21:37:56 Docker-1 NetworkManager[9811]: <info>  [1527647876.9788] device added (path: /sys/devices/virtual/net/veth0b3f2c6, iface: veth0b3f2c6): no ifupdown configuration found.
> May 29 21:37:56 Docker-1 NetworkManager[9811]: <info>  [1527647876.9805] manager: (vethc059b83): new Veth device (/org/freedesktop/NetworkManager/Devices/38170)
> May 29 21:37:56 Docker-1 dockerd[20640]: time="2018-05-29T21:37:56-05:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/7e534a290d8838942e5686ad2faf4d8215602edd0a27ae26641559c4f9d9d525/shim.sock" debug=false module="containerd/tasks" pid=10134
> May 29 21:37:56 Docker-1 NetworkManager[9811]: <info>  [1527647876.9927] manager: (veth0b3f2c6): new Veth device (/org/freedesktop/NetworkManager/Devices/38171)
> May 29 21:37:57 Docker-1 kernel: eth0: renamed from vethc059b83
> May 29 21:37:57 Docker-1 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth0b3f2c6: link becomes ready
> May 29 21:37:57 Docker-1 kernel: docker0: port 2(veth0b3f2c6) entered blocking state
> May 29 21:37:57 Docker-1 kernel: docker0: port 2(veth0b3f2c6) entered forwarding state
> May 29 21:37:57 Docker-1 kernel: audit: type=1400 audit(1527647877.493:250385): apparmor="DENIED" operation="open" profile="hassio-supervisor" name="/" pid=10155 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> May 29 21:37:57 Docker-1 audit[10155]: AVC apparmor="DENIED" operation="open" profile="hassio-supervisor" name="/" pid=10155 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> May 29 21:37:57 Docker-1 audit[10155]: AVC apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=10155 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:57 Docker-1 audit[10155]: AVC apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=10155 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:57 Docker-1 kernel: audit: type=1400 audit(1527647877.502:250386): apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=10155 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:57 Docker-1 kernel: audit: type=1400 audit(1527647877.503:250387): apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=10155 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:57 Docker-1 kernel: audit: type=1400 audit(1527647877.503:250388): apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=10155 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:57 Docker-1 audit[10155]: AVC apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=10155 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:57 Docker-1 audit[10155]: AVC apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=10155 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:57 Docker-1 audit[10155]: AVC apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/math.cpython-36m-x86_64-linux-gnu.so" pid=10155 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]: Traceback (most recent call last):
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/asyncio/__init__.py", line 9, in <module>
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:     from . import selectors
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]: ImportError: cannot import name 'selectors'
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]: During handling of the above exception, another exception occurred:
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]: Traceback (most recent call last):
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:     "__main__", mod_spec)
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:     exec(code, run_globals)
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/site-packages/hassio/__main__.py", line 2, in <module>
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:     import asyncio
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/asyncio/__init__.py", line 11, in <module>
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:     import selectors  # Will also be exported.
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:   File "/usr/lib/python3.6/selectors.py", line 10, in <module>
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]:     import math
> May 29 21:37:57 Docker-1 hassio-supervisor[9922]: ImportError: Error loading shared library /usr/lib/python3.6/lib-dynload/math.cpython-36m-x86_64-linux-gnu.so: Permission denied
> May 29 21:37:57 Docker-1 NetworkManager[9811]: <info>  [1527647877.6576] devices removed (path: /sys/devices/virtual/net/vethc059b83, iface: vethc059b83)
> May 29 21:37:57 Docker-1 NetworkManager[9811]: <info>  [1527647877.6582] device (vethc059b83): driver 'veth' does not support carrier detection.
> May 29 21:37:57 Docker-1 NetworkManager[9811]: <info>  [1527647877.6597] device (veth0b3f2c6): link connected
> May 29 21:37:57 Docker-1 dockerd[20640]: time="2018-05-29T21:37:57-05:00" level=info msg="shim reaped" id=7e534a290d8838942e5686ad2faf4d8215602edd0a27ae26641559c4f9d9d525 module="containerd/tasks"
> May 29 21:37:57 Docker-1 dockerd[20640]: time="2018-05-29T21:37:57.744757344-05:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
> May 29 21:37:57 Docker-1 kernel: vethc059b83: renamed from eth0
> May 29 21:37:57 Docker-1 kernel: docker0: port 2(veth0b3f2c6) entered disabled state
> May 29 21:37:57 Docker-1 kernel: docker0: port 2(veth0b3f2c6) entered disabled state
> May 29 21:37:57 Docker-1 kernel: device veth0b3f2c6 left promiscuous mode
> May 29 21:37:57 Docker-1 kernel: docker0: port 2(veth0b3f2c6) entered disabled state
> May 29 21:37:58 Docker-1 NetworkManager[9811]: <info>  [1527647878.1424] devices added (path: /sys/devices/virtual/net/vethc059b83, iface: vethc059b83)
> May 29 21:37:58 Docker-1 NetworkManager[9811]: <info>  [1527647878.1429] device added (path: /sys/devices/virtual/net/vethc059b83, iface: vethc059b83): no ifupdown configuration found.
> May 29 21:37:58 Docker-1 NetworkManager[9811]: <info>  [1527647878.1437] devices removed (path: /sys/devices/virtual/net/veth0b3f2c6, iface: veth0b3f2c6)
> May 29 21:37:58 Docker-1 NetworkManager[9811]: <info>  [1527647878.1455] devices removed (path: /sys/devices/virtual/net/vethc059b83, iface: vethc059b83)
> May 29 21:37:58 Docker-1 NetworkManager[9811]: <info>  [1527647878.2751] device (veth0b3f2c6): driver 'veth' does not support carrier detection.
> May 29 21:37:58 Docker-1 systemd[1]: hassio-supervisor.service: Main process exited, code=exited, status=1/FAILURE
> May 29 21:37:58 Docker-1 docker[10252]: hassio_supervisor
> May 29 21:37:58 Docker-1 systemd[1]: hassio-supervisor.service: Unit entered failed state.
> May 29 21:37:58 Docker-1 systemd[1]: hassio-supervisor.service: Failed with result 'exit-code'.
> ^C
> 

and 

> dmesg | tail

gets me this:

> [271124.997317] docker0: port 2(vethe6035bf) entered forwarding state
> [271125.646913] audit: type=1400 audit(1527648246.289:250769): apparmor="DENIED" operation="open" profile="hassio-supervisor" name="/" pid=22236 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> [271125.733913] audit: type=1400 audit(1527648246.376:250770): apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=22236 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> [271125.735104] audit: type=1400 audit(1527648246.378:250771): apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=22236 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> [271125.736049] audit: type=1400 audit(1527648246.378:250772): apparmor="DENIED" operation="file_mmap" profile="hassio-supervisor" name="/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so" pid=22236 comm="python3" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
> [271126.088694] docker0: port 2(vethe6035bf) entered disabled state
> [271126.088784] veth29e1ae2: renamed from eth0
> [271126.154119] docker0: port 2(vethe6035bf) entered disabled state
> [271126.156307] device vethe6035bf left promiscuous mode
> [271126.156313] docker0: port 2(vethe6035bf) entered disabled state
>

**Comment by pvizeli** [comment]
Rerun the installer. I fix this error
