### ISSUE TITLE
nginx-proxy/letsencrypt integration

### ISSUE THREAD

**Issue by thehomerepot** [home-assistant/hassio-build#89]
Is there a way to have the supervisor tag addons and homeassistant with the appropriate nginx-proxy and letsencrypt tags? This would automate the issue of certs. Example environment entries on a manually configured home-assistant docker container.

- VIRTUAL_HOST=hass.${DOMAIN_NAME}
- VIRTUAL_PORT=80
- VIRTUAL_PROTO=http
- LETSENCRYPT_HOST=hass.${DOMAIN_NAME}
- LETSENCRYPT_EMAIL=${EMAIL_ADDRESS}

Those values make hass.${DOMAIN_NAME} available on port 443 which proxies you to port 80 on the hass container. The ssl certificates are auto generated.

Info links below.
https://github.com/jwilder/nginx-proxy
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

**Comment by frenck** [comment]
Even if they did, you cannot access the Docker socket, so it would still not be possible to do stuff like this.

**Comment by thehomerepot** [comment]
The other docker container (nginx-proxy) accesses the docker socket. All I'm asking is the ability to have the supervisor container (which as I understand it manages the homeassistant and addon containers) include these environment variables. The other containers will monitor for those tags and auto generate certs and proxy traffic to them.

**Comment by frenck** [comment]
Again: None of the add-on access the Docker socket, since that is not possible in Hass.io.
So you request does not make sense. Tagging can be done, sure. But no add-on would be able to access those tags.

**Comment by frenck** [comment]
Ow, wait! Now I hit submit, it dawns on me. You are manually running these containers next / separate from Hass.io right?
That makes sense.

**Comment by frenck** [comment]
This actually could be possible as an add-on...
But it has some dependencies, which i've discussed a couple of days ago with pvizeli.

I'll get back to you as soon as possible.

**Comment by pvizeli** [comment]
My problem with this container solution is, that it make container useless. If a container have full access to docker api, he have more right as a root user and if that container also in front of the hole box... It's like a brean death of security specialist.

There are a simle solution, they I want integrate if I find time. You dock to hass.io service API and every add-on can provide his data to this service endpoint. A container with support this solutions can attach to this data and provide a proxy without full rights over the hole system.

**Comment by thehomerepot** [comment]
Are you referring to the nginx container having read-only access to the docker socket? Can you elaborate on the issue that causes? I don't understand what security risk is introduced with read-only access to the socket.

**Comment by pvizeli** [comment]
It exists no read-only rights to a socket. If you have no rights to ask docker for data, you never become data they you can read and for ask data, you need write permissions.

**Comment by thehomerepot** [comment]
Sorry, I can't comprehend what risk you're trying to explain.

**Comment by pvizeli** [comment]
Your proxy stay in front of all services (some time he should protect this services). It stay in the dmz or is available from internet. If a container have access to the docker socket, it have the high possible rights on your system. If this container will be hacked, the attacker have more as only full access to your system. In other words, if you use a proxy container like this, you can also map the other container directly to internet and have a better protection.

But if you don't use this kind of proxy to protect your system, yes it dosn't matters.

**Comment by thehomerepot** [comment]
Which container are you claiming has WRITE access to the docker socket?

**Comment by pvizeli** [comment]
https://twitter.com/Ben_Hall/status/706879493135323136

**Comment by lowey71** [comment]
The nginx-proxy container does not HAVE to have access to the docker socket.  Can use docker-gen to remove this requirement.
