### ISSUE TITLE
can't run on Pi3+

### ISSUE THREAD

**Issue by ngocgl** [home-assistant/hassio-build#90]
hi!

After install hassio with command:

curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s -- -m raspberrypi3-64

I got the follow error. Please help to fix it. Thanks

Jun 26 11:43:41 raspberrypi hassio-supervisor[3180]: 18-06-26 04:43:41 INFO (SyncWorker_5) [hassio.docker.interface] Pull image homeassistant/qemu-armhf-homeassistant tag landingpage.
Jun 26 11:43:45 raspberrypi dockerd[487]: time="2018-06-26T11:43:45.174328912+07:00" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Jun 26 11:43:45 raspberrypi dockerd[487]: time="2018-06-26T11:43:45.176456113+07:00" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
Jun 26 11:43:45 raspberrypi hassio-supervisor[3180]: 18-06-26 04:43:45 ERROR (SyncWorker_5) [hassio.docker.interface] Can't install homeassistant/qemu-armhf-homeassistant:landingpage -> 404 Client Error: Not Found ("pull access denied for homeassistant/qemu-armhf-homeassistant, repository does not exist or may require 'docker login'").
Jun 26 11:43:45 raspberrypi hassio-supervisor[3180]: 18-06-26 04:43:45 WARNING (MainThread) [hassio.homeassistant] Fails install landingpage, retry after 60sec

**Comment by frenck** [comment]
`-m raspberrypi3-64` is not a valid option.
try `-m aarch64`.

**Comment by ngocgl** [comment]
thanks frenck!

The image was installed successfully. The container is created but how I know it up & running?
I can't access HASSIO portal from external & withing pi.
When I tried to map port 8123 to host, I got the error below:

#docker run -p 8123:8123 homeassistant/armhf-hassio-supervisor
18-06-27 08:28:26 CRITICAL (MainThread) [hassio.bootstrap] Can't find SUPERVISOR_SHARE in env!

 any suggestion?

**Comment by ngocgl** [comment]
Here is the output of hass.io container.


root@raspberrypi:/home/pi# docker container inspect de026f112dc4
[
    {
        "Id": "de026f112dc4ee7764590a484f5f3697af705041ee767221d647ff41cfed6093",
        "Created": "2018-06-26T07:02:54.000141893Z",
        "Path": "python3",
        "Args": [
            "-m",
            "hassio"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 4528,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-06-27T08:23:23.698931681Z",
            "FinishedAt": "2018-06-27T08:23:10.655804712Z"
        },
        "Image": "sha256:7e86f8cf5eac0b9d6f83400859bc7a472c35b6d45f0c68722fc89677720ac4b6",
        "ResolvConfPath": "/var/lib/docker/containers/de026f112dc4ee7764590a484f5f3697af705041ee767221d647ff41cfed6093/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/de026f112dc4ee7764590a484f5f3697af705041ee767221d647ff41cfed6093/hostname",
        "HostsPath": "/var/lib/docker/containers/de026f112dc4ee7764590a484f5f3697af705041ee767221d647ff41cfed6093/hosts",
        "LogPath": "/var/lib/docker/containers/de026f112dc4ee7764590a484f5f3697af705041ee767221d647ff41cfed6093/de026f112dc4ee7764590a484f5f3697af705041ee767221d647ff41cfed6093-json.log",
        "Name": "/hassio_supervisor",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/run/docker.sock:/var/run/docker.sock",
                "/var/run/dbus:/var/run/dbus",
                "/usr/share/hassio:/data"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "apparmor=unconfined",
                "seccomp=unconfined"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/90be66c31a7f27e155485f578ac6867baf76c1442d2308c774417895fbb7d334-init/diff:/var/lib/docker/overlay2/cb8e23420d6d28e9bd70533baf2895e319c84a1d979293bd0824616726d6243e/diff:/var/lib/docker/overlay2/735eaefc99b2eb9b11581c3d820401ee053a4c2bfc68979b76649fd8b5ab67b1/diff:/var/lib/docker/overlay2/f2764f160235733741987e8e37fd621b87a23fbc5d3d5cff7198a729a68880ff/diff:/var/lib/docker/overlay2/c06186cb1be3a49bbd90533f6c70fc1c129c988bc345ffbe0c6201327a595ad6/diff:/var/lib/docker/overlay2/b8c4ce865b0f0fbcd46e233150d6938a091fd96de6f1fb7248a3aa4f37624bb9/diff:/var/lib/docker/overlay2/b31809019fab412ccdaffbf40c7c570f1443efc1ef28da63c375142e29000bb6/diff:/var/lib/docker/overlay2/46f9506b1df9b8783e8a9c102463eb20eb2a9c727853fbc8e52a309f405731dd/diff",
                "MergedDir": "/var/lib/docker/overlay2/90be66c31a7f27e155485f578ac6867baf76c1442d2308c774417895fbb7d334/merged",
                "UpperDir": "/var/lib/docker/overlay2/90be66c31a7f27e155485f578ac6867baf76c1442d2308c774417895fbb7d334/diff",
                "WorkDir": "/var/lib/docker/overlay2/90be66c31a7f27e155485f578ac6867baf76c1442d2308c774417895fbb7d334/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/usr/share/hassio",
                "Destination": "/data",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/dbus",
                "Destination": "/var/run/dbus",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "de026f112dc4",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "SUPERVISOR_SHARE=/usr/share/hassio",
                "SUPERVISOR_NAME=hassio_supervisor",
                "HOMEASSISTANT_REPOSITORY=homeassistant/raspberrypi3-64-homeassistant",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8"
            ],
            "Cmd": [
                "python3",
                "-m",
                "hassio"
            ],
            "ArgsEscaped": true,
            "Image": "homeassistant/armhf-hassio-supervisor",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "io.hass.arch": "armhf",
                "io.hass.type": "supervisor",
                "io.hass.version": "109"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "883452a5d3ee5dcf92c7cd2a4dc2328c51a66a85ed16de72172ae83001220172",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/883452a5d3ee",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "523d1d535a53fcc413f075bf17d3c872be125cba5a49a1462891fadd73fdee4c",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "b6b2f9866c6996434d0f5abca2a560ef1875caeb3f6aff0520d004c1e0c3de14",
                    "EndpointID": "523d1d535a53fcc413f075bf17d3c872be125cba5a49a1462891fadd73fdee4c",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                },
                "hassio": {
                    "IPAMConfig": {
                        "IPv4Address": "172.30.32.2"
                    },
                    "Links": null,
                    "Aliases": [
                        "hassio",
                        "de026f112dc4"
                    ],
                    "NetworkID": "2f89a90614ad8fe4f47e12d124904fb1fddeab12dd00e5385d98564f5434b312",
                    "EndpointID": "932bb35137c204cd182a981148c7690e987256598fbb0f850ad930eb10e82b79",
                    "Gateway": "172.30.32.1",
                    "IPAddress": "172.30.32.2",
                    "IPPrefixLen": 23,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:1e:20:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by pvizeli** [comment]
Look like you need reinstall your setup. You can't run the supervisor without the installer scripts. You can also use:
https://github.com/home-assistant/hassos
