### ISSUE TITLE
Support alternate registries

### ISSUE THREAD

**Issue by ndarilek** [home-assistant/hassio-build#92]
I'm attempting to use GitLab's internal registry. Authentication is successful, and a push should work. I have the following image set in config.json:

`"image": "registry.gitlab.com/ndarilek/hassio-mycroft/{arch}",`

What I see in my logs:

```
[INFO] Start upload registry.gitlab.com/ndarilek:2
[WARN] Upload fail!
```

Looks like the script is ignoring everything after the second /.

This registry and image should be publically accessible, so I don't think there's a conceptual reason that it shouldn't work. The builder should probably just not drop everything after the second /.

Thanks.

**Comment by frenck** [comment]
Are you passing on your local Docker socket?

**Comment by ndarilek** [comment]
No, but what difference would that make? I'm sharing my Docker
credentials. This isn't an authentication failure. The image should be
_registry.gitlab.com/ndarilek/hassio-mycroft/armhf_, not
_registry.gitlab.com/ndarilek_ (I.e. in the ndarilek/hassio-mycroft repo
on registry.gitlab.com, not under a user named registry.gitlab.com in
the ndarilek repo on hub.docker.com.)

I don't know if this would break Hassio later if it munges the "image"
field in a similar way.

Thanks.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-build/blob/master/builder/builder.sh#L325-L328

Yes. Feel free to fix it :)

**Comment by ndarilek** [comment]
Got it. I see lots of instances of `$REPOSITORY/$IMAGE`. Any reason why the image can't be treated as a full identifier? I.e. Just refer to `$IMAGE` everywhere and require that it be a valid specifier in the configuration. IIRC, without hostnames, Docker Hub is assumed on pulls/pushes.

That's the route I'll take if no one has issues with it. But it seems like the most obvious solution, so I thought I'd ask why it wasn't taken before just implementing the fix that way. :)

**Comment by pvizeli** [comment]
Yes, we split it because you can push a add-on/homeassistant/supervisor/ect container for test to another repository. That allow to build any kind of that stuff but overwrite the repository later on build process.

**Comment by ndarilek** [comment]
Would there be any opposition to just treating the image as a monolithic
piece (I.e. no repository-splitting?)

In GitLab's registry, registry.gitlab.com/ndarilek/hassio-mycroft,
registry.gitlab.com/ndarilek/hassio-mycroft/armhf and maybe even another
layer are valid images. In this case, what is the repository and what is
the image? registry.gitlab.com/ndarilek is the URL of my user account,
but you won't find my registry or images there.
registry.gitlab.com/ndarilek/hassio-mycroft is where the images live,
but I have several layers of namespacing. And that's just one
third-party image registry with its quirky rules. :)

I could change line 327 from:

```
        image="$(echo "$raw_image" | cut -f 2 -d '/')"
```

to

```
        image="$(echo "$raw_image" | cut -f 2- -d '/')"
```

and that would include everything after the first / as the image. But in
that case, my repository would be registry.gitlab.com and my image would
be ndarilek/hassio-mycroft/armhf, so you'd have two variables called
`repository` and `image`, neither of which is a repository or image. :)
Far better would be just treating the image as a single thing, then if
someone wants to manipulate part of one without changing the entire
thing, make that their problem/responsibility. :) At the end of the day,
it doesn't seem super complicated to simply have
homeassistant/hassio-addon-whatever and
homeassistant-testing/hassio-addon-whatever as separate strings, using
them whenever you want to push to another repo.

Thanks.
