### ISSUE TITLE
error install hassio - raspberry pi 3

### ISSUE THREAD

**Issue by lpt2007** [home-assistant/hassio-build#93]
When I run:
curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s -- -m raspberrypi3

I get error:
[Warning] No AppArmor support on Host.
[Warning] No NetworkManager support on Host.
[Info] Install supervisor docker
[Info] Install supervisor startup scripts
[Info] Run Hass.io
Failed to start hassio-supervisor.service: Unknown unit: hassio-supervisor.service
See system logs and 'systemctl status hassio-supervisor.service' for details.

systemctl status hassio-supervisor.service
Failed to get properties: No such interface ''

**Comment by pvizeli** [comment]
Need run script als root

**Comment by lpt2007** [comment]
Hi I run script as admin but result is the same.

Any other suggestions.

bdw my I try tu urun script on xbian.

uname -a
Linux rpi3 4.14.52+ #1 SMP PREEMPT Mon Jul 2 03:25:35 CEST 2018 armv7l GNU/Linux

**Comment by lpt2007** [comment]
I try to start service manually still same error:
root@rpi3 ~ # sudo systemctl start hassio-supervisor.service
Failed to start hassio-supervisor.service: Unknown unit: hassio-supervisor.service
See system logs and 'systemctl status hassio-supervisor.service' for details.

**Comment by pvizeli** [comment]
You need debug the install script to understand why he don't install the systemd service files on your xbian machine.

**Comment by elRadix** [comment]
same issue, folllowed the instructions as per readme file and running as root

> Linux dietpi 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux


```
Aug 14 14:49:19 dietpi systemd[1]: Starting Hass.io AppArmor...
Aug 14 14:49:19 dietpi hassio-apparmor[29754]: Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Aug 14 14:49:19 dietpi hassio-apparmor[29754]: Use --subdomainfs to override.
Aug 14 14:49:19 dietpi hassio-apparmor[29754]: [Error]: Can't load profile /usr/share/hassio/apparmor/hassio-supervisor
Aug 14 14:49:19 dietpi systemd[1]: Started Hass.io AppArmor.
```

below docker log of hassio_supervisor 

> 18-08-14 12:50:15 INFO (MainThread) [__main__] Initialize Hassio setup
> 18-08-14 12:50:15 INFO (MainThread) [hassio.docker.network] Can't find HassIO network, create new network
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 229, in _raise_for_status
>     response.raise_for_status()
>   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http+docker://localhost/v1.38/networks/create
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.7/site-packages/hassio/__main__.py", line 35, in <module>
>     coresys = bootstrap.initialize_coresys(loop)
>   File "/usr/local/lib/python3.7/site-packages/hassio/bootstrap.py", line 37, in initialize_coresys
>     coresys = CoreSys(loop)
>   File "/usr/local/lib/python3.7/site-packages/hassio/coresys.py", line 31, in __init__
>     self._docker = DockerAPI()
>   File "/usr/local/lib/python3.7/site-packages/hassio/docker/__init__.py", line 28, in __init__
>     self.network = DockerNetwork(self.docker)
>   File "/usr/local/lib/python3.7/site-packages/hassio/docker/network.py", line 20, in __init__
>     self.network = self._get_network()
>   File "/usr/local/lib/python3.7/site-packages/hassio/docker/network.py", line 60, in _get_network
>     "com.docker.network.bridge.name": DOCKER_NETWORK,
>   File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 154, in create
>     resp = self.client.api.create_network(name, *args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 152, in create_network
>     return self._result(res, json=True)
>   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 235, in _result
>     self._raise_for_status(response)
>   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 231, in _raise_for_status
>     raise create_api_error_from_http_exception(e)
>   File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
>     raise cls(e, response=response, explanation=explanation)
> docker.errors.APIError: 403 Client Error: Forbidden ("cannot create network ad39e01bea3170b4300d3f417022ec68203023b873584f32959fe5675f0c3935 (hassio): conflicts with network 97ecef0789c86376842b1f8e383d39cf7fd9132c1582c7da8a6693b25ea5e97d (br-97ecef0789c8): networks have overlapping IPv4")
> 18-08-14 12:50:15 ERROR (MainThread) [asyncio] Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x7535b950>
> 18-08-14 12:50:15 ERROR (MainThread) [asyncio] Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x754099d0>
> 18-08-14 12:50:26 INFO (MainThread) [__main__] Initialize Hassio setup
> 18-08-14 12:50:27 INFO (MainThread) [hassio.docker.network] Can't find HassIO network, create new network
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 229, in _raise_for_status
>     response.raise_for_status()
>   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http+docker://localhost/v1.38/networks/create
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.7/site-packages/hassio/__main__.py", line 35, in <module>
>     coresys = bootstrap.initialize_coresys(loop)
>   File "/usr/local/lib/python3.7/site-packages/hassio/bootstrap.py", line 37, in initialize_coresys
>     coresys = CoreSys(loop)
>   File "/usr/local/lib/python3.7/site-packages/hassio/coresys.py", line 31, in __init__
>     self._docker = DockerAPI()
>   File "/usr/local/lib/python3.7/site-packages/hassio/docker/__init__.py", line 28, in __init__
>     self.network = DockerNetwork(self.docker)
>   File "/usr/local/lib/python3.7/site-packages/hassio/docker/network.py", line 20, in __init__
>     self.network = self._get_network()
>   File "/usr/local/lib/python3.7/site-packages/hassio/docker/network.py", line 60, in _get_network
>     "com.docker.network.bridge.name": DOCKER_NETWORK,
>   File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 154, in create
>     resp = self.client.api.create_network(name, *args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 152, in create_network
>     return self._result(res, json=True)
>   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 235, in _result
>     self._raise_for_status(response)
>   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 231, in _raise_for_status
>     raise create_api_error_from_http_exception(e)
>   File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
>     raise cls(e, response=response, explanation=explanation)
> docker.errors.APIError: 403 Client Error: Forbidden ("cannot create network 9a94dde079193ebe34eefe9c0816d8e37caee4030fd3a73ee6823f8779418239 (hassio): conflicts with network 97ecef0789c86376842b1f8e383d39cf7fd9132c1582c7da8a6693b25ea5e97d (br-97ecef0789c8): networks have overlapping IPv4")
> 18-08-14 12:50:27 ERROR (MainThread) [asyncio] Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x75324a70>
> 18-08-14 12:50:27 ERROR (MainThread) [asyncio] Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x753478f0>
>
